// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorApp2.Migrations
{
    [DbContext(typeof(BlazorApp2Context))]
    [Migration("20240125154351_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorApp2.Models.Posetitel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("Возраст")
                        .HasColumnType("int");

                    b.Property<string>("Имя")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Комната")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Мини_бар")
                        .HasColumnType("int");

                    b.Property<string>("Отчество")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Питомец")
                        .HasColumnType("bit");

                    b.Property<string>("Размер_багажа")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Судимость")
                        .HasColumnType("bit");

                    b.Property<string>("Фамилия")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Фото")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Posetitel");
                });

            modelBuilder.Entity("BlazorApp2.Models.Student", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("Возраст")
                        .HasColumnType("int");

                    b.Property<string>("Группа")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("День_Рождения")
                        .HasColumnType("datetime2");

                    b.Property<string>("Имя")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Отчество")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Рост")
                        .HasColumnType("int");

                    b.Property<string>("Специальность")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Стипендия")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Фамилия")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
